### ISSUE TITLE
Method to anonymise EmbeddedDataFrame

### ISSUE THREAD

**Issue by matweldon** [datasciencecampus/pprl_toolkit#10]

**Comment by SStock1** [comment]
@matweldon would you be able to add a description to this.

**Comment by matweldon** [comment]
The app already does this -- it would just be a convenience function to tidy up the API:

Basically a method that removes any columns except 'bf_indices', 'thresholds' and 'bf_norms' (and a user-provided list of cols to keep)

```python
edf = EmbeddedDataFrame(df, embedder)
edf.anonymise()
# or edf.anonymise(cols_to_keep = ['idx']) to keep the 'idx' column
edf.to_json('path/to/file.json')
```
